// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Net.Http;
using Microsoft.Rest;
using NicheLens.Scrapper.Api.Client;

namespace NicheLens.Scrapper.Api.Client
{
    public partial class ScrapperApi : ServiceClient<ScrapperApi>, IScrapperApi
    {
        private Uri _baseUri;
        
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        public Uri BaseUri
        {
            get { return this._baseUri; }
            set { this._baseUri = value; }
        }
        
        private ServiceClientCredentials _credentials;
        
        /// <summary>
        /// Credentials for authenticating with the service.
        /// </summary>
        public ServiceClientCredentials Credentials
        {
            get { return this._credentials; }
            set { this._credentials = value; }
        }
        
        private IParser _parser;
        
        public virtual IParser Parser
        {
            get { return this._parser; }
        }
        
        private IScrapperOperations _scrapper;
        
        public virtual IScrapperOperations Scrapper
        {
            get { return this._scrapper; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ScrapperApi class.
        /// </summary>
        public ScrapperApi()
            : base()
        {
            this._parser = new Parser(this);
            this._scrapper = new ScrapperOperations(this);
            this._baseUri = new Uri("https://microsoft-apiapp9b2b9b0667ef43058cfe467f6b8d6828.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the ScrapperApi class.
        /// </summary>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public ScrapperApi(params DelegatingHandler[] handlers)
            : base(handlers)
        {
            this._parser = new Parser(this);
            this._scrapper = new ScrapperOperations(this);
            this._baseUri = new Uri("https://microsoft-apiapp9b2b9b0667ef43058cfe467f6b8d6828.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the ScrapperApi class.
        /// </summary>
        /// <param name='rootHandler'>
        /// Optional. The http client handler used to handle http transport.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public ScrapperApi(HttpClientHandler rootHandler, params DelegatingHandler[] handlers)
            : base(rootHandler, handlers)
        {
            this._parser = new Parser(this);
            this._scrapper = new ScrapperOperations(this);
            this._baseUri = new Uri("https://microsoft-apiapp9b2b9b0667ef43058cfe467f6b8d6828.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the ScrapperApi class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public ScrapperApi(Uri baseUri, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            this._baseUri = baseUri;
        }
        
        /// <summary>
        /// Initializes a new instance of the ScrapperApi class.
        /// </summary>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public ScrapperApi(ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
        
        /// <summary>
        /// Initializes a new instance of the ScrapperApi class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public ScrapperApi(Uri baseUri, ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._baseUri = baseUri;
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
    }
}
